server:
  port: 8081
dubbo:
  application:
    name: dubbo-springboot-rest-springmvc
    qos-port: 33333
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: tri
    port: 50052


logging:
  level:
    root: info